/*
 * generated by Xtext 2.26.0
 */
package composant.xtext.comp.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class CompProposalProvider extends AbstractCompProposalProvider {
}
