/*
 * generated by Xtext 2.26.0
 */
package composant.xtext.comp.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CompAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("composant/xtext/comp/parser/antlr/internal/InternalComp.tokens");
	}
}
