/*
 * generated by Xtext 2.26.0
 */
package composant.xtext.comp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CompUiModule extends AbstractCompUiModule {

	public CompUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
