/*
 * generated by Xtext 2.26.0
 */
package composant.xtext.comp;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CompStandaloneSetup extends CompStandaloneSetupGenerated {

	public static void doSetup() {
		new CompStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
