/*
 * generated by Xtext 2.26.0
 */
package composant.xtext.comp.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCompScopeProvider extends DelegatingScopeProvider {
}
